"""update

Revision ID: 372694827175
Revises: 1b30747157e5
Create Date: 2024-06-12 08:57:29.407565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372694827175'
down_revision = '1b30747157e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('postal_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('house_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('bus_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('bus_number')
        batch_op.drop_column('house_number')
        batch_op.drop_column('postal_number')
        batch_op.drop_column('street')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
