"""product table

Revision ID: 56915f7b3a2c
Revises: aacd01832f81
Create Date: 2024-04-11 18:54:24.283812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56915f7b3a2c'
down_revision = 'aacd01832f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_category', sa.String(length=120), nullable=True),
    sa.Column('product_description', sa.String(length=250), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_product_category'), ['product_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_description'), ['product_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_name'), ['product_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_product_price'), ['product_price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_product_description'))
        batch_op.drop_index(batch_op.f('ix_product_product_category'))

    op.drop_table('product')
    # ### end Alembic commands ###
