"""users table

Revision ID: aacd01832f81
Revises: abb51c923984
Create Date: 2024-04-10 09:47:49.113555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacd01832f81'
down_revision = 'abb51c923984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('postal_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('house_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('bus_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bus_number')
        batch_op.drop_column('house_number')
        batch_op.drop_column('postal_number')
        batch_op.drop_column('street')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
