"""Category table

Revision ID: ea363ab034e6
Revises: 56915f7b3a2c
Create Date: 2024-04-11 19:22:44.677498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea363ab034e6'
down_revision = '56915f7b3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_product_product_category')
        batch_op.drop_index('ix_product_product_description')
        batch_op.drop_index('ix_product_product_name')
        batch_op.drop_index('ix_product_product_price')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('product_category')
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_description')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_category', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_product_product_price', ['product_price'], unique=False)
        batch_op.create_index('ix_product_product_name', ['product_name'], unique=True)
        batch_op.create_index('ix_product_product_description', ['product_description'], unique=False)
        batch_op.create_index('ix_product_product_category', ['product_category'], unique=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    op.drop_table('category')
    # ### end Alembic commands ###
