"""update

Revision ID: fd64b0b3c3e3
Revises: 372694827175
Create Date: 2024-06-13 11:30:19.290741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd64b0b3c3e3'
down_revision = '372694827175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('postal_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('admin_rights',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin_rights',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('postal_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_order_id_fkey', 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
